# The unique identifier (UUID) must be unique!
# Use linux command uuidgen to create a random UUID
uuid = "61d7cd9b-d4f7-4fe1-9456-910700e29667"

# The name of the crosshair (will be shown at the editor)
name = "Example Crosshair"

# Use semantic versioning
version = "1.0.0"

# Use license identifiers (https://spdx.org/licenses/)
license = "CC-BY-NC-4.0"

# The authors who has created the crosshair
authors = [
    "Peter Penacka"
]

# The filename of the crosshair
filename = "crosshair.png"
